### ISSUE TITLE
有些APP使用 lyrebird 接口会加载超时

### ISSUE THREAD

**Issue by ly1012** [Meituan-Dianping/lyrebird#129]
**Describe the bug**
IOS 上打开“泰然金融”APP，无法展示“转让专区”的数据（接口访问失败）。

**To Reproduce**
1. Go to “出借”页面（底部按钮：出借）
2. Click on “转让专区”
3. 转让数据接口加载超时，提示加载失败
4. 使用美团外卖、微贷网等APP正常。

**Expected behavior**
转让专区的转让数据可以正常展示。

**Screenshots**

APP 报错截图：
![image](https://user-images.githubusercontent.com/19919579/55048701-1c2b0f80-5084-11e9-8fe4-7d13d6594b50.png)

Lyrebird 控制台报错信息：

```python
[2019-03-27 11:27:29,818] ERROR in app: Exception on /mock/http://::ffff:180.163.26.112/mmcrhead/oY4BHYs3iav1iaF215sYzJE7JickqzLY5G5ync5lLTJqiaZH9ZQfoO9az7pEphvoY9mdvz3ChbdsBOJLfuvmN93BAvVyJLEC31E3/0 [GET]
Traceback (most recent call last):
  File "d:\program\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\program\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\program\python37-32\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "d:\program\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\program\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\program\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\program\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\program\python37-32\lib\site-packages\lyrebird\mock\blueprints\api_mock.py", line 25, in index
    req_context = HandlerContext(request, path)
  File "d:\program\python37-32\lib\site-packages\lyrebird\mock\handlers\handler_context.py", line 40, in __init__
    self._parse_request()
  File "d:\program\python37-32\lib\site-packages\lyrebird\mock\handlers\handler_context.py", line 47, in _parse_request
    request_info = self._read_origin_request_info_from_url()
  File "d:\program\python37-32\lib\site-packages\lyrebird\mock\handlers\handler_context.py", line 84, in _read_origin_request_info_from_url
    port=parsed_path.port if parsed_path.port else '80',
  File "d:\program\python37-32\lib\urllib\parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: ':ffff:180.163.26.112'
```

**Smartphone:**
 - Device: iPhone6
 - OS: iOS12.1.4
 - App: 泰然金融
 - Version: V6.6.4

**lyrebird**
IP  10.200.4.26
MOCK.PORT  9090
PROXY.PORT  4272
VERSION  1.6.0

**Additional context**
其他APP，如：LinkedIn、铜板街、唯品会 也会加载超时。

LinkedIn：
![image](https://user-images.githubusercontent.com/19919579/55049598-e5ef8f00-5087-11e9-9e64-ce7e48291732.png)

铜板街：
![image](https://user-images.githubusercontent.com/19919579/55049645-07507b00-5088-11e9-8a31-d33b0f4a5b51.png)

唯品会：
![image](https://user-images.githubusercontent.com/19919579/55049676-1e8f6880-5088-11e9-8bc8-8565ce94da48.png)

**Comment by zhaoye** [comment]
你好：
非常感谢你的反馈。
还需要更多的信息帮助我们定位问题。
* 可否提供更多的日志？目前日志还看不出来上游错误产生的原因。
* 接入方式是怎样的？设置代理？

@ly1012

**Comment by ly1012** [comment]
@zhaoye 
1. 在 Windows 10 上通过 PowerShell 启动 lyrebird，启动命令：lyrebird -v 。
![image](https://user-images.githubusercontent.com/19919579/55123016-f3fee780-513b-11e9-844c-48ccfde7308e.png)
2. IOS 手机连接到公司内网 WiFi ，设置 lyrebird 代理如下：
![image](https://user-images.githubusercontent.com/19919579/55123218-a8990900-513c-11e9-8114-c8cb1d6b6208.png)
3. 访问 mitm.it 下载 https 证书，并信任 mitmproxy 证书。
4. 打开“泰然金融”APP，访问“出借”列表页面，提示接口加载超时。
5. 打开“美团外卖”APP，访问正常。
6. 再重启“泰然金融”APP，仍然访问失败。
7. lyrebird.log 日志请见附件。
[lyrebird.log](https://github.com/Meituan-Dianping/lyrebird/files/3015901/lyrebird.log)

**Comment by zhaoye** [comment]
@ly1012 

日志里面大部分是这个ssl连接被拒绝的错误。
```bash
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))
```
* 在调试https的请求之前有没有安装并信任证书呢？
* 另外APP是否对证书做了验证，没有允许私有证书连接？
* 可以使用 lyrebird -vvv 启动，以获得更多详细日志。

**Comment by ly1012** [comment]
@zhaoye 初步测试结果如下：
1. 调试前已安装并信任证书。
2. APP未对证书做验证。
3. 使用 lyrebird -vvv 启动，发起 https 请求时可以看到 proxy_flow 行，但未输出 handler_context 和 event 行日志（见错误日志和正常日志对比）。

**错误日志**
```
2019-03-29 14:33:16,470 INFO [proxy_flow] - Thread-3 [PID] 22016 - https://jrcg.trc.com/proxy/trc_bjcg/app/operation/switch
2019-03-29 14:33:16,471 INFO [proxy_flow] - Thread-3 [PID] 22016 - Redirect-> http://localhost:9090/mock/https://jrcg.trc.com/proxy/trc_bjcg/app/operation/switch
```

**正常日志**
```
2019-03-29 14:33:16,321 INFO [proxy_flow] - Thread-3 [PID] 22016 - https://stats.cn.ronghub.com/active.json
2019-03-29 14:33:16,321 INFO [proxy_flow] - Thread-3 [PID] 22016 - Redirect-> http://localhost:9090/mock/https://stats.cn.ronghub.com/active.json
2019-03-29 14:33:17,428 DEBUG [handler_context] - Thread-245 [PID] 22016 - [On client request] https://stats.cn.ronghub.com/active.json
2019-03-29 14:33:17,463 DEBUG [event] - Thread-245 [PID] 22016 - channel=flow state=False
message:
-----------
{'name': 'client.request', 'time': 1553841197.4290519, 'id': '0f796ea7-175b-4ded-956f-307db9d7ee0a', 'flow': {'id': '38bcf187-d608-4d29-a87f-b1534c5c7309', 'size': 0, 'duration': 0, 'start_time': 1553841197.4250624, 'client_address': '192.168.43.185', 'request': {'headers': {'Host': 'localhost', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '91', 'Accept': '*/*', 'User-Agent': 'TairanFinanceProject/6.6.4.0 CFNetwork/976 Darwin/18.2.0', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'br, gzip, deflate', 'Connection': 'keep-alive', 'Lyrebird-Client-Address': '192.168.43.185'}, 'method': 'POST', 'query': ImmutableMultiDict([]), 'url': 'https://stats.cn.ronghub.com/active.json', 'scheme': 'https', 'host': 'stats.cn.ronghub.com', 'port': '80', 'path': '/active.json', 'data': {'deviceId': 'c45d4152bb383575ea765a245d1b10ee4e09452c', 'appKey': 'sfci50a7s8vji', 'timestamp': '1553840536'}}}, 'channel': 'flow', 'timestamp': 1553841197, 'sender': {'file': 'd:\\program\\python37-32\\lib\\site-packages\\lyrebird\\mock\\blueprints\\api_mock.py', 'function': 'index'}}
-----------
```

有时间我再进行一次详细的测试（1. 使用其他手机；2. 直接使用 mitmproxy；3. 使用 fiddler），谢谢。

**Comment by zhaoye** [comment]
收到。已复现。感谢 @ly1012

**Comment by zhaoye** [comment]
Fixed by #130

**Comment by ly1012** [comment]
测试通过，问题已修复。@zhaoye

**Comment by zhaoye** [comment]
十分感谢支持Lyrebird改进 @ly1012
