### ISSUE TITLE
KeyError: 'Session is disconnected'

### ISSUE THREAD

**Issue by reeyur** [Meituan-Dianping/lyrebird#146]
**Describe the bug**
Traceback (most recent call last):
  File "/Users/yurree/.lyrebird/tools/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 302, in run_wsgi
    execute(self.server.app)
  File "/Users/yurree/.lyrebird/tools/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 290, in execute
    application_iter = app(environ, start_response)
  File "/Users/yurree/.lyrebird/tools/venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/yurree/.lyrebird/tools/venv/lib/python3.7/site-packages/flask_socketio/__init__.py", line 44, in __call__
    start_response)
  File "/Users/yurree/.lyrebird/tools/venv/lib/python3.7/site-packages/engineio/middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/Users/yurree/.lyrebird/tools/venv/lib/python3.7/site-packages/socketio/server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/Users/yurree/.lyrebird/tools/venv/lib/python3.7/site-packages/engineio/server.py", line 337, in handle_request
    socket = self._get_socket(sid)
  File "/Users/yurree/.lyrebird/tools/venv/lib/python3.7/site-packages/engineio/server.py", line 521, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

**To Reproduce**
1. 控制台输入的日志显示如上错误

**Comment by zhaoye** [comment]
前端socketio断开，不影响使用
