### ISSUE TITLE
write db failed: database disk image is malformed

### ISSUE THREAD

**Issue by zhaoye** [Meituan-Dianping/lyrebird#165]
**Describe the bug**
write DB fail:
`
Save event failed. Traceback (most recent call last):
 File "/Users/?/.lyrebird/tools/venv/lib/python3.6/site-packages/lyrebird/db/database_server.py", line 59, in run
   session.commit()
 File "/Users/?/.lyrebird/tools/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1026, in commit
   self.transaction.commit()
 File "/Users/?/.lyrebird/tools/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 491, in commit
   self._assert_active(prepared_ok=True)
 File "/Users/?/.lyrebird/tools/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 294, in _assert_active
   % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO event (channel, event_id, content, timestamp) VALUES (?, ?, ?, ?)]
[parameters: ('android.device', '11516?5c', '[{"id": "?", "info": {"product": "?", "model": "?", "os": "7.0", "ip": "", "resolution": "1080x1920"}, "app": {"packageName": "?", "startActivity": "?", "version": "?"}}]', '2019-05-29 16:29:51.227460')]
(Background on this error at: http://sqlalche.me/e/4xp6)
`

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by zhaoye** [comment]
### The DB file was broken:

1.Delete DB file
```
rm ~/.lyrebird/lyrebird.db
```
2.Restart lyrebird

### TODO
* Lyrebird can auto dump data and then write data to a new db file, remove the broken db file.
