### ISSUE TITLE
重名接口,但是请求方式不同,mock返回不能区分

### ISSUE THREAD

**Issue by yufengTester** [Meituan-Dianping/lyrebird#307]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by youngfreeFJS** [comment]
您可以在 DataManger -> Information -> rule 中，规定 request.method 对相同 path 的不同请求类型进行区分，如图所示。
![image](https://user-images.githubusercontent.com/46949537/77852246-2d1add80-7210-11ea-93e6-1d95290d8ab2.png)

**Comment by yufengTester** [comment]
按照你提供的办法能区分请求了,但页面没有展示 
**
Exception ignored in: <generator object stream_with_context.<locals>.generator at 0x12B27F30>
Traceback (most recent call last):
  File "E:\Program Files\python3.7\lib\site-packages\flask\helpers.py", line 166, in generator
    gen.close()
  File "E:\Program Files\python3.7\lib\site-packages\flask\ctx.py", line 464, in __exit__
    self.auto_pop(exc_value)
  File "E:\Program Files\python3.7\lib\site-packages\flask\ctx.py", line 452, in auto_pop
    self.pop(exc)
  File "E:\Program Files\python3.7\lib\site-packages\flask\ctx.py", line 438, in pop
    app_ctx.pop(exc)
  File "E:\Program Files\python3.7\lib\site-packages\flask\ctx.py", line 241, in pop
    assert rv is self, "Popped wrong app context.  (%r instead of %r)" % (rv, self)
AssertionError: Popped wrong app context.  (None instead of <flask.ctx.AppContext object at 0x12B38610>)
[2020-03-31 14:26:08,845] ERROR in app: Exception on /mock/http://pre.myweimai.com/dpm/patient_info/detail [GET]
Traceback (most recent call last):
  File "E:\Program Files\python3.7\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Program Files\python3.7\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Program Files\python3.7\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "E:\Program Files\python3.7\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Program Files\python3.7\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\Program Files\python3.7\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Program Files\python3.7\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\workspace\lyrebird\lyrebird\mock\blueprints\core.py", line 38, in index
    mock_handler.handle(req_context)
  File "E:\workspace\lyrebird\lyrebird\mock\handlers\mock_handler.py", line 15, in handle
    hit_datas = context.application.data_manager.get_matched_data(handler_context.flow)
  File "E:\workspace\lyrebird\lyrebird\mock\dm.py", line 161, in get_matched_data
    resp_data_template = Template(response_data['response']['data'])
  File "E:\Program Files\python3.7\lib\site-packages\jinja2\environment.py", line 1031, in __new__
    return env.from_string(source, template_class=cls)
  File "E:\Program Files\python3.7\lib\site-packages\jinja2\environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "E:\Program Files\python3.7\lib\site-packages\jinja2\environment.py", line 629, in compile
    source = self._generate(source, name, filename, defer_init=defer_init)
  File "E:\Program Files\python3.7\lib\site-packages\jinja2\environment.py", line 592, in _generate
    optimized=self.optimized,
  File "E:\Program Files\python3.7\lib\site-packages\jinja2\compiler.py", line 83, in generate
    raise TypeError("Can't compile non template nodes")
TypeError: Can't compile non template nodes
**

**Comment by youngfreeFJS** [comment]
> File "E:\workspace\lyrebird\lyrebird\mock\dm.py", line 161, in get_matched_data
> resp_data_template = Template(response_data['response']['data'])
> 
> File "E:\Program Files\python3.7\lib\site-packages\jinja2\compiler.py", line 83, in generate
> raise TypeError("Can't compile non template nodes")
> TypeError: Can't compile non template nodes
> 

目前看来是jinjia2在处理接口返回值data的时候抛出了异常，可否提供脱敏的：接口请求与返回的数据结果进行进一步的问题排查呢？

另，建议对您上述日志文件中的一些如域名等敏感信息，也进行脱敏处理，保证您的信息安全～

**Comment by yufengTester** [comment]
谢谢你的提醒.
第一个接口:
Request:
{
    "url": "http://www.mock.com/detail?customerRegId=911800000297023447&familyCustomerId=",
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "zh-cn",
        "Access-Control-Request-Headers": date,origin,sessionid,token,version",
        "Access-Control-Request-Method": "GET",
        "Connection": "keep-alive",
        "Content-Length": "0",
        "Host": "localhost",
        "Lyrebird-Client-Address": "172.16.20.11",
        "Origin": "http://www.mock.com",
        "Proxy-Connection": "keep-alive",
        "Referer": "http://www.mock.com?customerRegId=911800000297023447",

    },
    "method": "OPTIONS"
}
ResponseDate
无

第二个接口:
Request:
{
    "url": "http://www.mock.com/detail?customerRegId=911800000297023447&familyCustomerId=",
    "headers": {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "zh-cn",
        "Connection": "keep-alive",
        "Host": "localhost",
        "Lyrebird-Client-Address": "172.16.20.11",
        "Origin": "http://www.mock.com",
        "Proxy-Connection": "keep-alive",
        "Referer": "http://www.mock.com?customerRegId=911800000297023447",
        "Date": "1585634284752",
        "Origin": "H5",
        "Sessionid": "",
        "Token": "fa716182-bbb7-4111-8132-1d89eb98b123",
        "Version": "1.0.0"
    },
    "method": "GET"
}
ResponseDate
{
    "code": 0,
    "data": {
        "age": 21,
        "consultNum": 0,
        "customerId": "911800000297023111",
        "doctorId": "1478374368882114222",
        "familyCustomers": [
            {
                "age": 21,
                "customerId": "911800000297023333",
                "gender": "男",
                "name": "张三测试"
            }
        ],
        "focus": false,
        "followupNum": 0,
        "gender": "男",
        "patientName": "张三测试",
        "photo": "",
        "remark": "",
        "tagVoList": []
    },
    "message": ""
}

**Comment by youngfreeFJS** [comment]
这是一个bug，团队的同学在release1.9.5版本已fix #320

**Comment by youngfreeFJS** [comment]
hi
这是一个bug，目前最新版本已修复，可以下载最新版本测试验收一下
如果还有其他问题的话，我们再进行同步，
感谢您的反馈～～

**Comment by youngfreeFJS** [comment]
@yufengTester 
最新版 release v1.9.6 进行解决，对于PR： #322
