### ISSUE TITLE
请求页面的时候是乱码，直接用mitmproxy没问题

### ISSUE THREAD

**Issue by cxapython** [Meituan-Dianping/lyrebird#420]
### 具体日志信息看下面
```
INFO [mitm] https://www.douyin.com/
INFO [mitm] Redirect-> http://127.0.0.1:9090/mock/https://www.douyin.com/
INFO [proxy_handler] <Proxy> https://www.douyin.com/
Exception ignored in: <generator object stream_with_context.<locals>.generator at 0x11278ae60>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/helpers.py", line 166, in generator
    gen.close()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/ctx.py", line 464, in __exit__
    self.auto_pop(exc_value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/ctx.py", line 452, in auto_pop
    self.pop(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/ctx.py", line 438, in pop
    app_ctx.pop(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/ctx.py", line 241, in pop
    assert rv is self, "Popped wrong app context.  (%r instead of %r)" % (rv, self)
AssertionError: Popped wrong app context.  (None instead of <flask.ctx.AppContext object at 0x111b2b400>)
```

**Comment by zhaoye** [comment]
本地环境 py3.8未复现， 待使用py3.6尝试复现

**Comment by zhaoye** [comment]
py3.6未复现

**Comment by zhaoye** [comment]
可以提供更多日志吗？
@cxapython
