### ISSUE TITLE
无法启动lyrebird服务，报错:json.decoder.JSONDecodeError: Invalid \escape: line 6 column 21 (char 119)

### ISSUE THREAD

**Issue by AllenLuosong** [Meituan-Dianping/lyrebird#423]
Hi Dear Al:
 I got an problem like tihs，can anyone have a idea to it. thank you.

**Description**
通过pip install lyrebird安装好后 dos界面执行 lyrebird报错如下
C:\Users\Administrator\test>lyrebird -v
Traceback (most recent call last):
  File "d:\program files\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python\Python37\Scripts\lyrebird.exe\__main__.py", line 7, in <module>
  File "d:\program files\python\python37\lib\site-packages\lyrebird\manager.py", line 98, in main
    application._cm = ConfigManager()
  File "d:\program files\python\python37\lib\site-packages\lyrebird\config.py", line 37, in __init__

    self.read_config()
  File "d:\program files\python\python37\lib\site-packages\lyrebird\config.py", line 61, in read_con
fig
    self.config_root), download_dir=str(self.ROOT/'downloads')))
  File "d:\program files\python\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "d:\program files\python\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\program files\python\python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 6 column 21 (char 119)

**To Reproduce**
dos界面界面执行 lyrebird报错

**Desktop (please complete the following information):**
 - Version Python 3.7.4，lyrebird  1.16.3

**Comment by zhaoye** [comment]
目前对Windows支持不是很好，读取配置文件时解析路径出了些问题。

**Comment by zhaoye** [comment]
Fixed #435
