### ISSUE TITLE
启动的时候报错 no Module name 'resource'

### ISSUE THREAD

**Issue by mooncakedevop** [Meituan-Dianping/lyrebird#651]
**Description**
启动的时候报错

Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hp\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\.virtualenvs\lyrebird-9UyizO4m\Scripts\lyrebird.exe\__main__.py", line 4, in <module>
  File "C:\Users\HP\.virtualenvs\lyrebird-9UyizO4m\lib\site-packages\lyrebird\__init__.py", line 1, in <module>
    from .manager import main, run
  File "C:\Users\HP\.virtualenvs\lyrebird-9UyizO4m\lib\site-packages\lyrebird\manager.py", line 8, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

**Desktop **
 - OS: [Windows 10 19044.1706]
 - python 3.7.9

**Comment by zhaoye** [comment]
Fixed #373 on 2020
看起是比较旧的版本。请确认使用最新的版本 @mooncakedevop
