### ISSUE TITLE
start version 2.9.2 failed

### ISSUE THREAD

**Issue by GalvinChen** [Meituan-Dianping/lyrebird#693]
Traceback (most recent call last):
  File "/opt/homebrew/bin/lyrebird", line 5, in <module>
    from lyrebird.manager import main
  File "/opt/homebrew/lib/python3.10/site-packages/lyrebird/__init__.py", line 1, in <module>
    from .manager import main, run
  File "/opt/homebrew/lib/python3.10/site-packages/lyrebird/manager.py", line 23, in <module>
    from lyrebird.mock.mock_server import LyrebirdMockServer
  File "/opt/homebrew/lib/python3.10/site-packages/lyrebird/mock/mock_server.py", line 3, in <module>
    from .blueprints.apis import api
  File "/opt/homebrew/lib/python3.10/site-packages/lyrebird/mock/blueprints/apis/__init__.py", line 2, in <module>
    from flask_restful import Api
  File "/opt/homebrew/lib/python3.10/site-packages/flask_restful/__init__.py", line 17, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

**Comment by zhaoye** [comment]
2.9.2 not support Python3.10 yet.
We will support it on #688 
@GalvinChen

**Comment by zhaoye** [comment]
Fixed  #688
