### ISSUE TITLE
[BUG]  ImportError: cannot import name 'ParameterSource' from 'click.core'（Python3.8.11）

### ISSUE THREAD

**Issue by youngfreeFJS** [Meituan-Dianping/lyrebird#751]
**Description**
ImportError: cannot import name 'ParameterSource' from 'click.core'（Python3.8.11）

**To Reproduce**
1. Use Python3.8.11 Run Master Code (Version 2.13.0)

**Expected behavior**
Start Success.

**Screenshots**
```Python
2023-04-11 19:40:48,580 /Users/freeyoung/Desktop/codes/github/lyrebird/lyrebird/mock/extra_mock_server/server.py:142
NOTICE Extra mock server start on 9999
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 8, in <module>
    sys.exit(mitmdump())
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/_main.py", line 153, in mitmdump
    from mitmproxy.tools import dump
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/dump.py", line 1, in <module>
    from mitmproxy import addons
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/addons/__init__.py", line 12, in <module>
    from mitmproxy.addons import onboarding
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/addons/onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/addons/onboardingapp/__init__.py", line 3, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 34, in <module>
    from . import cli
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 15, in <module>
    from click.core import ParameterSource
ImportError: cannot import name 'ParameterSource' from 'click.core' (/usr/local/lib/python3.8/site-packages/click/core.py)
2023-04-11 19:41:18,795 /Users/freeyoung/Desktop/codes/github/lyrebird/lyrebird/mitm/proxy_server.py:25
ERROR Start mitmdump failed.
Please check your mitmdump file /usr/local/bin/mitmdump
2023-04-11 19:41:18,799 /Users/freeyoung/Desktop/codes/github/lyrebird/lyrebird/event.py:168
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by youngfreeFJS** [comment]
it seems mitmdump dependency error.
```Shell
➜  .ssh /usr/local/bin/mitmdump -v
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 8, in <module>
    sys.exit(mitmdump())
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/_main.py", line 153, in mitmdump
    from mitmproxy.tools import dump
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/tools/dump.py", line 1, in <module>
    from mitmproxy import addons
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/addons/__init__.py", line 12, in <module>
    from mitmproxy.addons import onboarding
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/addons/onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/addons/onboardingapp/__init__.py", line 3, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 34, in <module>
    from . import cli
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 15, in <module>
    from click.core import ParameterSource
ImportError: cannot import name 'ParameterSource' from 'click.core' (/usr/local/lib/python3.8/site-packages/click/core.py)
➜  .ssh
```

**Comment by youngfreeFJS** [comment]
problem solved by ```rm -rf /usr/local/bin/mitmdump```
