### ISSUE TITLE
Windows 安装报错

### ISSUE THREAD

**Issue by Bugaoxingxx** [Meituan-Dianping/lyrebird#9]
```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\lyrebird.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\lyrebird\manager.py", line 219, in run
    fire.Fire(CommandLine, 'v start')
  File "c:\programdata\anaconda3\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "c:\programdata\anaconda3\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "c:\programdata\anaconda3\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\lyrebird\manager.py", line 159, in __init__
    self.server = Server()
  File "c:\programdata\anaconda3\lib\site-packages\lyrebird\manager.py", line 48, in __init__
    init_logger_settings()
  File "c:\programdata\anaconda3\lib\site-packages\lyrebird\mock\logger_helper.py", line 42, in init_logger_settings
    disable_existing_loggers=False)
  File "c:\programdata\anaconda3\lib\logging\config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "c:\programdata\anaconda3\lib\logging\config.py", line 147, in _install_handlers
    args = eval(args, vars(logging))
  File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

看起来像是没有对windows目录进行转义

**Comment by zhaoye** [comment]
Windows环境确实还没有适配。已标记为缺陷。

**Comment by zhaoye** [comment]
已修复
